name = "microlab"
description = "Microlab blueprint for RHEL for Edge, tested on RHEL 8.7"
version = "0.0.0"
modules = []
distro = ""

[[packages]]
name = "ansible-core"
version = "*"

[[packages]]
name = "cockpit"
version = "*"

[[packages]]
name = "cockpit-composer"
version = "*"

[[packages]]
name = "cockpit-dashboard"
version = "*"

[[packages]]
name = "cockpit-machines"
version = "*"

[[packages]]
name = "cockpit-packagekit"
version = "*"

[[packages]]
name = "cockpit-podman"
version = "*"

[[packages]]
name = "cockpit-system"
version = "*"

[[packages]]
name = "cri-o"
version = "*"

[[packages]]
name = "firefox"
version = "*"

[[packages]]
name = "greenboot-rpm-ostree-grub2"
version = "*"

[[packages]]
name = "kernel"
version = "*"

[[packages]]
name = "kernel-core"
version = "*"

[[packages]]
name = "libguestfs-tools"
version = "*"

[[packages]]
name = "microshift"
version = "*"

[[packages]]
name = "nginx"
version = "*"

[[packages]]
name = "nmap"
version = "*"

[[packages]]
name = "nvidia-driver"
version = "515.105.01-1.el8.x86_64.rpm"

[[packages]]
name = "openshift-clients"
version = "*"

[[packages]]
name = "subscription-manager"
version = "*"

[[packages]]
name = "subscription-manager-cockpit"
version = "*"

[[packages]]
name = "subscription-manager-plugin-ostree"
version = "*"

[[groups]]
name = "GNOME"

[[groups]]
name = "Standard"

[[groups]]
name = "base-x"

[[groups]]
name = "Headless Management"

[[groups]]
name = "GNOME"

[[groups]]
name = "Virtualization Hypervisor"

[[groups]]
name = "Virtualization Tools"

[[groups]]
name = "Virtualization Client"

[[groups]]
name = "Virtualization Platform"

[[groups]]
name = "Container Management"

[[groups]]
name = "Hardware Monitoring Utilities"

[customizations]
hostname = "microlab.local"

[[customizations.user]]
name = "admin"
password = ""
key = "<ssh public key>"
groups = ["wheel"]
